#pragma once

#include "../common/types.hpp"
#include "../logger/logger.hpp"

namespace exchange {

class TradeFeed {
public:
    // Consume trade fills generated by the matching engine and publish/log them
    static void publish_trade(const Fill& fill) {
        LOG_INFO("[TRADE FEED] Trade Executed: TradeID=" + std::to_string(fill.trade_id) +
                 " Symbol=" + fill.symbol + " Qty=" + std::to_string(fill.quantity) +
                 " Price=" + std::to_string(fill.price) +
                 " BuyOrderID=" + std::to_string(fill.buy_order_id) +
                 " SellOrderID=" + std::to_string(fill.sell_order_id));
    }
};

} // namespace exchange
